routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('districts', 'DistrictController');

Route::resource('garbageBanks', 'GarbageBankController');

Route::resource('garbagePriceHistories', 'GarbagePriceHistoryController');

Route::resource('garbageTypes', 'GarbageTypesController');

Route::resource('villages', 'VillageController');

Route::resource('zones', 'ZonesController');


Route::resource('villages', 'VillageController');

app/Models/GarbageBank.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="GarbageBank",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="village_id",
 *          description="village_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="address",
 *          description="address",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="active",
 *          description="active",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="photo",
 *          description="photo",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="customer_count",
 *          description="customer_count",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="latitude",
 *          description="latitude",
 *          type="number",
 *          format="number"
 *      ),
 *      @SWG\Property(
 *          property="longitude",
 *          description="longitude",
 *          type="number",
 *          format="number"
 *      ),
 *      @SWG\Property(
 *          property="pin",
 *          description="pin",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="information",
 *          description="information",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="contact_person",
 *          description="contact_person",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class GarbageBank extends Model
{
    use SoftDeletes;

    public $table = 'garbage_banks';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'village_id',
        'name',
        'address',
        'active',
        'photo',
        'customer_count',
        'latitude',
        'longitude',
        'pin',
        'information',
        'contact_person'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'village_id' => 'integer',
        'name' => 'string',
        'address' => 'string',
        'active' => 'boolean',
        'photo' => 'string',
        'customer_count' => 'integer',
        'latitude' => 'float',
        'longitude' => 'float',
        'pin' => 'boolean',
        'information' => 'string',
        'contact_person' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/GarbageBankController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGarbageBankRequest;
use App\Http\Requests\UpdateGarbageBankRequest;
use App\Repositories\GarbageBankRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class GarbageBankController extends AppBaseController
{
    /** @var  GarbageBankRepository */
    private $garbageBankRepository;

    public function __construct(GarbageBankRepository $garbageBankRepo)
    {
        $this->garbageBankRepository = $garbageBankRepo;
    }

    /**
     * Display a listing of the GarbageBank.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $garbageBanks = $this->garbageBankRepository->all();

        return view('garbage_banks.index')
            ->with('garbageBanks', $garbageBanks);
    }

    /**
     * Show the form for creating a new GarbageBank.
     *
     * @return Response
     */
    public function create()
    {
        return view('garbage_banks.create');
    }

    /**
     * Store a newly created GarbageBank in storage.
     *
     * @param CreateGarbageBankRequest $request
     *
     * @return Response
     */
    public function store(CreateGarbageBankRequest $request)
    {
        $input = $request->all();

        $garbageBank = $this->garbageBankRepository->create($input);

        Flash::success('Garbage Bank saved successfully.');

        return redirect(route('garbageBanks.index'));
    }

    /**
     * Display the specified GarbageBank.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $garbageBank = $this->garbageBankRepository->find($id);

        if (empty($garbageBank)) {
            Flash::error('Garbage Bank not found');

            return redirect(route('garbageBanks.index'));
        }

        return view('garbage_banks.show')->with('garbageBank', $garbageBank);
    }

    /**
     * Show the form for editing the specified GarbageBank.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $garbageBank = $this->garbageBankRepository->find($id);

        if (empty($garbageBank)) {
            Flash::error('Garbage Bank not found');

            return redirect(route('garbageBanks.index'));
        }

        return view('garbage_banks.edit')->with('garbageBank', $garbageBank);
    }

    /**
     * Update the specified GarbageBank in storage.
     *
     * @param int $id
     * @param UpdateGarbageBankRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateGarbageBankRequest $request)
    {
        $garbageBank = $this->garbageBankRepository->find($id);

        if (empty($garbageBank)) {
            Flash::error('Garbage Bank not found');

            return redirect(route('garbageBanks.index'));
        }

        $garbageBank = $this->garbageBankRepository->update($request->all(), $id);

        Flash::success('Garbage Bank updated successfully.');

        return redirect(route('garbageBanks.index'));
    }

    /**
     * Remove the specified GarbageBank from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $garbageBank = $this->garbageBankRepository->find($id);

        if (empty($garbageBank)) {
            Flash::error('Garbage Bank not found');

            return redirect(route('garbageBanks.index'));
        }

        $this->garbageBankRepository->delete($id);

        Flash::success('Garbage Bank deleted successfully.');

        return redirect(route('garbageBanks.index'));
    }
}

resources/views/garbage_banks/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Bank
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'garbageBanks.store']) !!}

                        @include('garbage_banks.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_banks/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Bank
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($garbageBank, ['route' => ['garbageBanks.update', $garbageBank->id], 'method' => 'patch']) !!}

                        @include('garbage_banks.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/garbage_banks/fields.blade.php
<!-- Village Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('village_id', 'Village Id:') !!}
    {!! Form::number('village_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<!-- Active Field -->
<div class="form-group col-sm-6">
    {!! Form::label('active', 'Active:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('active', 0) !!}
        {!! Form::checkbox('active', '1', null) !!}
    </label>
</div>


<!-- Photo Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('photo', 'Photo:') !!}
    {!! Form::textarea('photo', null, ['class' => 'form-control']) !!}
</div>

<!-- Customer Count Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_count', 'Customer Count:') !!}
    {!! Form::number('customer_count', null, ['class' => 'form-control']) !!}
</div>

<!-- Latitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::number('latitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Longitude Field -->
<div class="form-group col-sm-6">
    {!! Form::label('longitude', 'Longitude:') !!}
    {!! Form::number('longitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Pin Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pin', 'Pin:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('pin', 0) !!}
        {!! Form::checkbox('pin', '1', null) !!}
    </label>
</div>


<!-- Information Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('information', 'Information:') !!}
    {!! Form::textarea('information', null, ['class' => 'form-control']) !!}
</div>

<!-- Contact Person Field -->
<div class="form-group col-sm-6">
    {!! Form::label('contact_person', 'Contact Person:') !!}
    {!! Form::text('contact_person', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('garbageBanks.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/garbage_banks/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Garbage Banks</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('garbageBanks.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('garbage_banks.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/garbage_banks/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Bank
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('garbage_banks.show_fields')
                    <a href="{!! route('garbageBanks.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_banks/show_fields.blade.php
<!-- Village Id Field -->
<div class="form-group">
    {!! Form::label('village_id', 'Village Id:') !!}
    <p>{!! $garbageBank->village_id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $garbageBank->name !!}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{!! $garbageBank->address !!}</p>
</div>

<!-- Active Field -->
<div class="form-group">
    {!! Form::label('active', 'Active:') !!}
    <p>{!! $garbageBank->active !!}</p>
</div>

<!-- Photo Field -->
<div class="form-group">
    {!! Form::label('photo', 'Photo:') !!}
    <p>{!! $garbageBank->photo !!}</p>
</div>

<!-- Customer Count Field -->
<div class="form-group">
    {!! Form::label('customer_count', 'Customer Count:') !!}
    <p>{!! $garbageBank->customer_count !!}</p>
</div>

<!-- Latitude Field -->
<div class="form-group">
    {!! Form::label('latitude', 'Latitude:') !!}
    <p>{!! $garbageBank->latitude !!}</p>
</div>

<!-- Longitude Field -->
<div class="form-group">
    {!! Form::label('longitude', 'Longitude:') !!}
    <p>{!! $garbageBank->longitude !!}</p>
</div>

<!-- Pin Field -->
<div class="form-group">
    {!! Form::label('pin', 'Pin:') !!}
    <p>{!! $garbageBank->pin !!}</p>
</div>

<!-- Information Field -->
<div class="form-group">
    {!! Form::label('information', 'Information:') !!}
    <p>{!! $garbageBank->information !!}</p>
</div>

<!-- Contact Person Field -->
<div class="form-group">
    {!! Form::label('contact_person', 'Contact Person:') !!}
    <p>{!! $garbageBank->contact_person !!}</p>
</div>

resources/views/garbage_banks/table.blade.php
<div class="table-responsive">
    <table class="table" id="garbageBanks-table">
        <thead>
            <tr>
                <th>Village Id</th>
        <th>Name</th>
        <th>Address</th>
        <th>Active</th>
        <th>Photo</th>
        <th>Customer Count</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Pin</th>
        <th>Information</th>
        <th>Contact Person</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($garbageBanks as $garbageBank)
            <tr>
                <td>{!! $garbageBank->village_id !!}</td>
            <td>{!! $garbageBank->name !!}</td>
            <td>{!! $garbageBank->address !!}</td>
            <td>{!! $garbageBank->active !!}</td>
            <td>{!! $garbageBank->photo !!}</td>
            <td>{!! $garbageBank->customer_count !!}</td>
            <td>{!! $garbageBank->latitude !!}</td>
            <td>{!! $garbageBank->longitude !!}</td>
            <td>{!! $garbageBank->pin !!}</td>
            <td>{!! $garbageBank->information !!}</td>
            <td>{!! $garbageBank->contact_person !!}</td>
                <td>
                    {!! Form::open(['route' => ['garbageBanks.destroy', $garbageBank->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('garbageBanks.show', [$garbageBank->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('garbageBanks.edit', [$garbageBank->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>