routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('districts', 'DistrictController');

Route::resource('garbageBanks', 'GarbageBankController');

Route::resource('garbagePriceHistories', 'GarbagePriceHistoryController');

Route::resource('garbageTypes', 'GarbageTypesController');

Route::resource('villages', 'VillageController');

Route::resource('zones', 'ZonesController');


Route::resource('villages', 'VillageController');

app/Models/GarbagePriceHistory.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="GarbagePriceHistory",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="garbage_type_id",
 *          description="garbage_type_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="garbage_bank_id",
 *          description="garbage_bank_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="date",
 *          description="date",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="price",
 *          description="price",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class GarbagePriceHistory extends Model
{
    use SoftDeletes;

    public $table = 'garbage_price_histories';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'garbage_type_id',
        'garbage_bank_id',
        'date',
        'price'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'garbage_type_id' => 'integer',
        'garbage_bank_id' => 'integer',
        'date' => 'datetime',
        'price' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/GarbagePriceHistoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGarbagePriceHistoryRequest;
use App\Http\Requests\UpdateGarbagePriceHistoryRequest;
use App\Repositories\GarbagePriceHistoryRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class GarbagePriceHistoryController extends AppBaseController
{
    /** @var  GarbagePriceHistoryRepository */
    private $garbagePriceHistoryRepository;

    public function __construct(GarbagePriceHistoryRepository $garbagePriceHistoryRepo)
    {
        $this->garbagePriceHistoryRepository = $garbagePriceHistoryRepo;
    }

    /**
     * Display a listing of the GarbagePriceHistory.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $garbagePriceHistories = $this->garbagePriceHistoryRepository->all();

        return view('garbage_price_histories.index')
            ->with('garbagePriceHistories', $garbagePriceHistories);
    }

    /**
     * Show the form for creating a new GarbagePriceHistory.
     *
     * @return Response
     */
    public function create()
    {
        return view('garbage_price_histories.create');
    }

    /**
     * Store a newly created GarbagePriceHistory in storage.
     *
     * @param CreateGarbagePriceHistoryRequest $request
     *
     * @return Response
     */
    public function store(CreateGarbagePriceHistoryRequest $request)
    {
        $input = $request->all();

        $garbagePriceHistory = $this->garbagePriceHistoryRepository->create($input);

        Flash::success('Garbage Price History saved successfully.');

        return redirect(route('garbagePriceHistories.index'));
    }

    /**
     * Display the specified GarbagePriceHistory.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $garbagePriceHistory = $this->garbagePriceHistoryRepository->find($id);

        if (empty($garbagePriceHistory)) {
            Flash::error('Garbage Price History not found');

            return redirect(route('garbagePriceHistories.index'));
        }

        return view('garbage_price_histories.show')->with('garbagePriceHistory', $garbagePriceHistory);
    }

    /**
     * Show the form for editing the specified GarbagePriceHistory.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $garbagePriceHistory = $this->garbagePriceHistoryRepository->find($id);

        if (empty($garbagePriceHistory)) {
            Flash::error('Garbage Price History not found');

            return redirect(route('garbagePriceHistories.index'));
        }

        return view('garbage_price_histories.edit')->with('garbagePriceHistory', $garbagePriceHistory);
    }

    /**
     * Update the specified GarbagePriceHistory in storage.
     *
     * @param int $id
     * @param UpdateGarbagePriceHistoryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateGarbagePriceHistoryRequest $request)
    {
        $garbagePriceHistory = $this->garbagePriceHistoryRepository->find($id);

        if (empty($garbagePriceHistory)) {
            Flash::error('Garbage Price History not found');

            return redirect(route('garbagePriceHistories.index'));
        }

        $garbagePriceHistory = $this->garbagePriceHistoryRepository->update($request->all(), $id);

        Flash::success('Garbage Price History updated successfully.');

        return redirect(route('garbagePriceHistories.index'));
    }

    /**
     * Remove the specified GarbagePriceHistory from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $garbagePriceHistory = $this->garbagePriceHistoryRepository->find($id);

        if (empty($garbagePriceHistory)) {
            Flash::error('Garbage Price History not found');

            return redirect(route('garbagePriceHistories.index'));
        }

        $this->garbagePriceHistoryRepository->delete($id);

        Flash::success('Garbage Price History deleted successfully.');

        return redirect(route('garbagePriceHistories.index'));
    }
}

resources/views/garbage_price_histories/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Price History
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'garbagePriceHistories.store']) !!}

                        @include('garbage_price_histories.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_price_histories/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Price History
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($garbagePriceHistory, ['route' => ['garbagePriceHistories.update', $garbagePriceHistory->id], 'method' => 'patch']) !!}

                        @include('garbage_price_histories.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/garbage_price_histories/fields.blade.php
<!-- Garbage Type Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('garbage_type_id', 'Garbage Type Id:') !!}
    {!! Form::number('garbage_type_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Garbage Bank Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('garbage_bank_id', 'Garbage Bank Id:') !!}
    {!! Form::number('garbage_bank_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date', 'Date:') !!}
    {!! Form::date('date', null, ['class' => 'form-control','id'=>'date']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'Price:') !!}
    {!! Form::number('price', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('garbagePriceHistories.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/garbage_price_histories/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Garbage Price Histories</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('garbagePriceHistories.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('garbage_price_histories.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/garbage_price_histories/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Price History
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('garbage_price_histories.show_fields')
                    <a href="{!! route('garbagePriceHistories.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_price_histories/show_fields.blade.php
<!-- Garbage Type Id Field -->
<div class="form-group">
    {!! Form::label('garbage_type_id', 'Garbage Type Id:') !!}
    <p>{!! $garbagePriceHistory->garbage_type_id !!}</p>
</div>

<!-- Garbage Bank Id Field -->
<div class="form-group">
    {!! Form::label('garbage_bank_id', 'Garbage Bank Id:') !!}
    <p>{!! $garbagePriceHistory->garbage_bank_id !!}</p>
</div>

<!-- Date Field -->
<div class="form-group">
    {!! Form::label('date', 'Date:') !!}
    <p>{!! $garbagePriceHistory->date !!}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', 'Price:') !!}
    <p>{!! $garbagePriceHistory->price !!}</p>
</div>

resources/views/garbage_price_histories/table.blade.php
<div class="table-responsive">
    <table class="table" id="garbagePriceHistories-table">
        <thead>
            <tr>
                <th>Garbage Type Id</th>
        <th>Garbage Bank Id</th>
        <th>Date</th>
        <th>Price</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($garbagePriceHistories as $garbagePriceHistory)
            <tr>
                <td>{!! $garbagePriceHistory->garbage_type_id !!}</td>
            <td>{!! $garbagePriceHistory->garbage_bank_id !!}</td>
            <td>{!! $garbagePriceHistory->date !!}</td>
            <td>{!! $garbagePriceHistory->price !!}</td>
                <td>
                    {!! Form::open(['route' => ['garbagePriceHistories.destroy', $garbagePriceHistory->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('garbagePriceHistories.show', [$garbagePriceHistory->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('garbagePriceHistories.edit', [$garbagePriceHistory->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>