routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('districts', 'DistrictController');

Route::resource('garbageBanks', 'GarbageBankController');

Route::resource('garbagePriceHistories', 'GarbagePriceHistoryController');

Route::resource('garbageTypes', 'GarbageTypesController');

Route::resource('villages', 'VillageController');

Route::resource('zones', 'ZonesController');


Route::resource('villages', 'VillageController');

app/Http/Controllers/GarbageTypesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateGarbageTypesRequest;
use App\Http\Requests\UpdateGarbageTypesRequest;
use App\Repositories\GarbageTypesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class GarbageTypesController extends AppBaseController
{
    /** @var  GarbageTypesRepository */
    private $garbageTypesRepository;

    public function __construct(GarbageTypesRepository $garbageTypesRepo)
    {
        $this->garbageTypesRepository = $garbageTypesRepo;
    }

    /**
     * Display a listing of the GarbageTypes.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $garbageTypes = $this->garbageTypesRepository->all();

        return view('garbage_types.index')
            ->with('garbageTypes', $garbageTypes);
    }

    /**
     * Show the form for creating a new GarbageTypes.
     *
     * @return Response
     */
    public function create()
    {
        return view('garbage_types.create');
    }

    /**
     * Store a newly created GarbageTypes in storage.
     *
     * @param CreateGarbageTypesRequest $request
     *
     * @return Response
     */
    public function store(CreateGarbageTypesRequest $request)
    {
        $input = $request->all();

        $garbageTypes = $this->garbageTypesRepository->create($input);

        Flash::success('Garbage Types saved successfully.');

        return redirect(route('garbageTypes.index'));
    }

    /**
     * Display the specified GarbageTypes.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $garbageTypes = $this->garbageTypesRepository->find($id);

        if (empty($garbageTypes)) {
            Flash::error('Garbage Types not found');

            return redirect(route('garbageTypes.index'));
        }

        return view('garbage_types.show')->with('garbageTypes', $garbageTypes);
    }

    /**
     * Show the form for editing the specified GarbageTypes.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $garbageTypes = $this->garbageTypesRepository->find($id);

        if (empty($garbageTypes)) {
            Flash::error('Garbage Types not found');

            return redirect(route('garbageTypes.index'));
        }

        return view('garbage_types.edit')->with('garbageTypes', $garbageTypes);
    }

    /**
     * Update the specified GarbageTypes in storage.
     *
     * @param int $id
     * @param UpdateGarbageTypesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateGarbageTypesRequest $request)
    {
        $garbageTypes = $this->garbageTypesRepository->find($id);

        if (empty($garbageTypes)) {
            Flash::error('Garbage Types not found');

            return redirect(route('garbageTypes.index'));
        }

        $garbageTypes = $this->garbageTypesRepository->update($request->all(), $id);

        Flash::success('Garbage Types updated successfully.');

        return redirect(route('garbageTypes.index'));
    }

    /**
     * Remove the specified GarbageTypes from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $garbageTypes = $this->garbageTypesRepository->find($id);

        if (empty($garbageTypes)) {
            Flash::error('Garbage Types not found');

            return redirect(route('garbageTypes.index'));
        }

        $this->garbageTypesRepository->delete($id);

        Flash::success('Garbage Types deleted successfully.');

        return redirect(route('garbageTypes.index'));
    }
}

resources/views/garbage_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Types
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'garbageTypes.store']) !!}

                        @include('garbage_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Types
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($garbageTypes, ['route' => ['garbageTypes.update', $garbageTypes->id], 'method' => 'patch']) !!}

                        @include('garbage_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/garbage_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('garbageTypes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/garbage_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Garbage Types</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('garbageTypes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('garbage_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/garbage_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Garbage Types
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('garbage_types.show_fields')
                    <a href="{!! route('garbageTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/garbage_types/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $garbageTypes->name !!}</p>
</div>

resources/views/garbage_types/table.blade.php
<div class="table-responsive">
    <table class="table" id="garbageTypes-table">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($garbageTypes as $garbageTypes)
            <tr>
                <td>{!! $garbageTypes->name !!}</td>
                <td>
                    {!! Form::open(['route' => ['garbageTypes.destroy', $garbageTypes->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('garbageTypes.show', [$garbageTypes->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('garbageTypes.edit', [$garbageTypes->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>